import * as img from "./images";

export const MATH = [
  { k: "", v: "/", i: img.fraction },
  { k: "sup", v: "^", i: "" },
  { k: "sub", v: "_", i: "" },
  { k: "√", v: "\\sqrt", i: "" },
  { k: "sin", v: "\\sin", i: "" },
  { k: "cos", v: "\\cos", i: "" },
  { k: "tan", v: "\\tan", i: "" },
  { k: "π", v: "\\pi", i: "" },
  { k: "≠", v: "\\neq", i: "" },
  { k: "×", v: "\\times", i: "" },
  { k: "÷", v: "\\div", i: "" },
  { k: "±", v: "±", i: "" },
  { k: ">", v: ">", i: "" },
  { k: "<", v: "<", i: "" },
  { k: "≥", v: "\\geq", i: "" },
  { k: "≤", v: "\\leq", i: "" },
  { k: ",", v: ",", i: "" },
  { k: ":", v: ":", i: "" },
  { k: "°", v: "\\degree", i: "" },
  { k: "x", v: "x", i: "" },
  { k: "y", v: "y", i: "" },
  { k: "∑", v: "\\sum", i: "" },
  { k: "∠", v: "∠", i: "" },
  { k: "∵", v: "\\because", i: "" },
  { k: "∴", v: "\\therefore", i: "" },
  { k: "∈", v: "\\in", i: "" },
  { k: "∉", v: "\\notin", i: "" },
  { k: "∩", v: "\\intersection", i: "" },
  { k: "∪", v: "\\cup", i: "" },
  { k: "⊂", v: "\\subset", i: "" },
  { k: "⊃", v: "\\superset", i: "" },
  { k: "∞", v: "\\infty", i: "" },
  { k: "log", v: "\\log", i: "" },
  { k: "←", v: "\\leftarrow", i: "" },
  { k: "→", v: "\\rightarrow", i: "" },
  { k: "⇔", v: "\\iff", i: "" },
];